### PR TITLE
added syntax check

### PR DESCRIPTION
**Pull request by pimvdnoll**
based on https://www.npmjs.com/package/gulp-jsvalidate

### CODE REVIEW

**Comment by JelteMX** [comment]
Added in [2.0.4](https://github.com/mendix/generator-mendix/releases/tag/v2.0.4). Thanks!

**Comment by pimvdnoll** [comment]
How do I update to this newest version? tried npm update generator-mendix but it has still the old package.json and gulp.js file

**Comment by JelteMX** [comment]
First you need to update your generator:

```cmd
npm update generator-mendix -g
```

after that, run ``yo mendix`` in the folder with the Gulpfile.js and package.json. You can always check the version of the generator you used by checking ``package.json`` in your widgetfolder.  This version number is also mentioned at the to of your Gulpfile.js. Look for 

```json
"generatorVersion": "2.0.4",
```

**Comment by pimvdnoll** [comment]
thanks, was not aware of running yo mendix again.

**Pull request merged**
